# Generated by Django 3.1.2 on 2020-10-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
