# Generated by Django 3.1.2 on 2020-10-22 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201023_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared',
            field=models.ForeignKey(blank=True, default=[], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='post.post'),
        ),
    ]
