# Generated by Django 3.1.2 on 2020-10-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201023_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to='post.post'),
        ),
    ]
